name: Final Build APK
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install
        run: npm install

      - name: 🚀 Build APK (No Questions)
        run: |
          npx eas-cli project:init --non-interactive
          npx eas-cli build --platform android --profile preview --local --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📥 Get APK
        uses: actions/upload-artifact@v4
        with:
          name: my-messenger-apk
          path: ./*.apk 
